const fs = require("fs");
const { QUERY_FILE_PATH, PAYLOAD_FILE_PATH } = require("./constants");
const { logger } = require("./logger");
async function readPayload() {
  try {
    const data = await fs.promises.readFile(PAYLOAD_FILE_PATH);
    if (data.byteLength > 0) {
      const jsonObj = JSON.parse(data);
      return jsonObj;
    }
  } catch (error) {
    logger.error(error);
    throw new Error(
      `Error reading or parsing JSON file with filename '${filename}': ${error}`
    );
  }
}

async function readParams() {
  try {
    const data = await fs.promises.readFile(QUERY_FILE_PATH);
    if (data.byteLength > 0) {
      const jsonObj = JSON.parse(data);
      return jsonObj;
    }
  } catch (error) {
    logger.error(error);
    throw new Error(
      `Error reading or parsing JSON file with filename '${filename}': ${error}`
    );
  }
}

function toQuery(json) {
    /**
     *  @argument json
     *  example;
     *      {
     *          'firstName': 'bassam';
     *          'age':  '30';   
     *      }
     * 
     *  @returns string
     *  example; 
     *      firstName=bassam&age=30
     */
  let params = [];
  for (let key in json) {
    params.push(`${key}=${json[key]}`);
  }
  return params.join("&");
}

function getPath(params, fix_params, path, requestNumber) {
  /**   
   *    @argument params        = dynamic params which has been generated by the tool.
   *    @argument fix_params    = fixed params which has been avoided by the tool.
   *    @argument path          = request path as it's been provided by the user.
   *    @argument requestNumber = increment mechansim for request tracking purposes.
   * 
   *    trying to meet all 4 difference cases
   *        1. There are neither dynamic params and fix params.
   *        2. There are both dynamic params and fix params.
   *        3. There are dynamic params but no fix params.
   *        4. There are fix params and no dynamic params.
   */
  if (!params && !fix_params) {
    return path;
  } else if (params && !fix_params) {
    return path + "?" + toQuery(params[requestNumber]);
  } else if (params && fix_params) {
    return path + "?" + toQuery(params[requestNumber]) + "&" + fix_params;
  } else if (!params && fix_params) {
    return path + "?" + fix_params;
  }
}

function removeGeneratedData() {
    /**
     *  Deleting created dummy files after a full benchmarking cycle.
     * 
     *  @todo: only clearing the file would be enough to reduce writing to disk
     */
      fs.unlink(QUERY_FILE_PATH, () => {})
      fs.unlink(PAYLOAD_FILE_PATH, () => {})
  }

module.exports = { readParams, readPayload, getPath, toQuery, removeGeneratedData }