name: Build Binaries

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build for Windows (x64)
        run: npx pkg --targets=node14-win-x64 .

      - name: Build for Windows (x86)
        run: npx pkg --targets=node14-win-x86 .

      - name: Build for macOS (x64)
        run: npx pkg --targets=node14-macos-x64 .

      - name: Build for macOS (arm64)
        run: npx pkg --targets=node14-macos-arm64 .

      - name: Build for Linux (x64)
        run: npx pkg --targets=node14-linux-x64 .

      - name: Build for Linux (x86)
        run: npx pkg --targets=node14-linux-x86 .
